/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BBreadcrumb: typeof import('bootstrap-vue-next')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next')['BBreadcrumbItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSidebar: typeof import('bootstrap-vue-next')['BSidebar']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    FooterButton: typeof import('./src/components/common/FooterButton.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IMaterialSymbolsDeleteForever: typeof import('~icons/material-symbols/delete-forever')['default']
    IMaterialSymbolsEditSquareOutlineRounded: typeof import('~icons/material-symbols/edit-square-outline-rounded')['default']
    IMaterialSymbolsHome: typeof import('~icons/material-symbols/home')['default']
    IMaterialSymbolsPerson: typeof import('~icons/material-symbols/person')['default']
    IMdiUserMultiple: typeof import('~icons/mdi/user-multiple')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
